### ISSUE TITLE
Deployment using EB

### ISSUE THREAD

**Issue by jobinthomasnypl** [NYPL-discovery/recap-harvester#6]

**Comment by nodanaonlyzuul** [comment]
Hey @jobinthomasnypl....just doing some spring cleaning in this repo.
I'm not sure what this issue means - maybe we can close it?

Our README documents how to deploy on EB and we'll soon be adding how to deploy it for nightly accessions/deaccessions.

**Comment by jobinthomasnypl** [comment]
Sorry this issue should be either closed or updated to deployment for services that do accession and deaccession.

**Comment by nodanaonlyzuul** [comment]
I think we can close this and make the appropriate updates regarding accession and deaccession in an upcoming pull request
